/**
 * email-mcp — Silver-tier Email MCP Server
 *
 * Tools:
 *   send_email(to, subject, body, attachment_path?)
 *     → Sends immediately via Gmail API. Supports file attachments.
 *
 *   draft_email(to, subject, body, attachment_path?)
 *     → Saves to Gmail Drafts (for human approval before sending).
 *     → Returns a draft_id so the user can review/send from Gmail.
 *
 * Auth:
 *   Reads credentials.json + token.json from project root.
 *   Run `node auth.js` once to generate token.json.
 *   Token is auto-refreshed on expiry — no manual steps needed.
 *
 * Protocol: Model Context Protocol v1 (stdio transport)
 *
 * Usage:
 *   node index.js          ← started by Claude Code automatically
 *   node auth.js           ← one-time OAuth2 setup
 */

import { readFileSync, existsSync } from "fs";
import { readFile }                 from "fs/promises";
import path                         from "path";
import { fileURLToPath }            from "url";
import { google }                   from "googleapis";
import { Server }                   from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport }     from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------
const __dirname  = path.dirname(fileURLToPath(import.meta.url));
const VAULT_ROOT = path.resolve(__dirname, "..");
const CREDS_FILE = path.join(VAULT_ROOT, "credentials.json");
const TOKEN_FILE = path.join(VAULT_ROOT, "token.json");

// ---------------------------------------------------------------------------
// Gmail OAuth2 client (reads credentials.json + token.json from project root)
// ---------------------------------------------------------------------------

function loadOAuth2Client() {
  // 1. Load credentials.json
  if (!existsSync(CREDS_FILE)) {
    throw new Error(
      `credentials.json not found at ${CREDS_FILE}.\n` +
      "Download from Google Cloud Console (OAuth2 Desktop App)."
    );
  }
  const creds = JSON.parse(readFileSync(CREDS_FILE, "utf8"));
  const { client_id, client_secret, redirect_uris } = creds.installed ?? creds.web;

  const oauth2 = new google.auth.OAuth2(
    client_id,
    client_secret,
    redirect_uris?.[0] ?? "http://localhost"
  );

  // 2. Load token.json (generated by auth.js or Python watchers)
  if (!existsSync(TOKEN_FILE)) {
    throw new Error(
      `token.json not found at ${TOKEN_FILE}.\n` +
      "Run: node email-mcp/auth.js"
    );
  }
  const tokens = JSON.parse(readFileSync(TOKEN_FILE, "utf8"));
  oauth2.setCredentials(tokens);

  // 3. Auto-save refreshed tokens back to token.json
  oauth2.on("tokens", (newTokens) => {
    const merged = { ...tokens, ...newTokens };
    try {
      require("fs").writeFileSync(TOKEN_FILE, JSON.stringify(merged, null, 2), "utf8");
    } catch { /* non-fatal */ }
    log("Token refreshed and saved.");
  });

  return oauth2;
}

function buildGmailService() {
  const auth = loadOAuth2Client();
  return google.gmail({ version: "v1", auth });
}

// ---------------------------------------------------------------------------
// MIME builder — supports plain-text and single attachment
// ---------------------------------------------------------------------------

const BOUNDARY = "==silver_tier_mcp_boundary==";

/**
 * Build a base64url-encoded RFC 2822 / MIME message.
 * If attachmentPath is provided, builds multipart/mixed with the file attached.
 */
async function buildRawMessage({ from, to, cc, subject, body, attachmentPath }) {
  const hasAttachment = Boolean(attachmentPath);

  if (!hasAttachment) {
    // Simple plain-text message
    const lines = [
      `From: ${from}`,
      `To: ${to}`,
      ...(cc ? [`Cc: ${cc}`] : []),
      `Subject: ${subject}`,
      "MIME-Version: 1.0",
      "Content-Type: text/plain; charset=UTF-8",
      "Content-Transfer-Encoding: 7bit",
      "",
      body,
    ];
    return toBase64url(lines.join("\r\n"));
  }

  // Multipart/mixed — body + attachment
  const filename = path.basename(attachmentPath);
  let fileBuffer;
  try {
    fileBuffer = await readFile(attachmentPath);
  } catch (err) {
    throw new Error(`Cannot read attachment at "${attachmentPath}": ${err.message}`);
  }
  const mimeType = guessMimeType(filename);
  const fileB64  = fileBuffer.toString("base64");

  const parts = [
    `--${BOUNDARY}`,
    "Content-Type: text/plain; charset=UTF-8",
    "Content-Transfer-Encoding: 7bit",
    "",
    body,
    "",
    `--${BOUNDARY}`,
    `Content-Type: ${mimeType}; name="${filename}"`,
    "Content-Transfer-Encoding: base64",
    `Content-Disposition: attachment; filename="${filename}"`,
    "",
    // Split base64 into 76-char lines (RFC 2045)
    fileB64.match(/.{1,76}/g).join("\r\n"),
    "",
    `--${BOUNDARY}--`,
  ];

  const headers = [
    `From: ${from}`,
    `To: ${to}`,
    ...(cc ? [`Cc: ${cc}`] : []),
    `Subject: ${subject}`,
    "MIME-Version: 1.0",
    `Content-Type: multipart/mixed; boundary="${BOUNDARY}"`,
    "",
  ];

  return toBase64url([...headers, ...parts].join("\r\n"));
}

function toBase64url(str) {
  return Buffer.from(str)
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

function guessMimeType(filename) {
  const ext = path.extname(filename).toLowerCase();
  const map = {
    ".pdf":  "application/pdf",
    ".doc":  "application/msword",
    ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ".xls":  "application/vnd.ms-excel",
    ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ".png":  "image/png",
    ".jpg":  "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif":  "image/gif",
    ".txt":  "text/plain",
    ".csv":  "text/csv",
    ".zip":  "application/zip",
    ".json": "application/json",
  };
  return map[ext] ?? "application/octet-stream";
}

// ---------------------------------------------------------------------------
// Gmail actions
// ---------------------------------------------------------------------------

async function sendEmail({ to, subject, body, cc, attachmentPath }) {
  const gmail = buildGmailService();
  const from  = await getMyEmail(gmail);
  const raw   = await buildRawMessage({ from, to, cc, subject, body, attachmentPath });

  const res = await gmail.users.messages.send({
    userId: "me",
    requestBody: { raw },
  });

  return {
    messageId: res.data.id,
    threadId:  res.data.threadId,
    labelIds:  res.data.labelIds ?? [],
    from,
  };
}

async function draftEmail({ to, subject, body, cc, attachmentPath }) {
  const gmail = buildGmailService();
  const from  = await getMyEmail(gmail);
  const raw   = await buildRawMessage({ from, to, cc, subject, body, attachmentPath });

  const res = await gmail.users.drafts.create({
    userId: "me",
    requestBody: {
      message: { raw },
    },
  });

  return {
    draftId:   res.data.id,
    messageId: res.data.message?.id,
    from,
  };
}

// Cache the "me" email so we don't call profile API on every send
let _myEmail = null;
async function getMyEmail(gmail) {
  if (_myEmail) return _myEmail;
  try {
    const profile = await gmail.users.getProfile({ userId: "me" });
    _myEmail = profile.data.emailAddress;
    log(`Authenticated as: ${_myEmail}`);
    return _myEmail;
  } catch {
    return process.env.GMAIL_FROM ?? "me@gmail.com";
  }
}

// ---------------------------------------------------------------------------
// Tool schemas
// ---------------------------------------------------------------------------

const sharedEmailProps = {
  to: {
    type: "string",
    description: "Recipient email address (comma-separated for multiple).",
  },
  subject: {
    type: "string",
    description: "Email subject line.",
  },
  body: {
    type: "string",
    description: "Plain-text email body.",
  },
  cc: {
    type: "string",
    description: "(Optional) CC addresses, comma-separated.",
  },
  attachment_path: {
    type: "string",
    description:
      "(Optional) Absolute path to a file to attach (PDF, DOCX, PNG, CSV, etc.).",
  },
};

const TOOLS = [
  {
    name: "send_email",
    description:
      "Send an email immediately via Gmail API. " +
      "Supports optional file attachment. " +
      "Returns Gmail message ID and thread ID on success.",
    inputSchema: {
      type: "object",
      properties: sharedEmailProps,
      required: ["to", "subject", "body"],
    },
  },
  {
    name: "draft_email",
    description:
      "Save an email as a Gmail Draft (does NOT send). " +
      "Use this when the email needs human review/approval before sending. " +
      "Returns a draft_id — the user can open Gmail to review and send. " +
      "Supports optional file attachment.",
    inputSchema: {
      type: "object",
      properties: sharedEmailProps,
      required: ["to", "subject", "body"],
    },
  },
];

// ---------------------------------------------------------------------------
// MCP Server
// ---------------------------------------------------------------------------

const server = new Server(
  { name: "email-mcp", version: "2.0.0" },
  { capabilities: { tools: {} } }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools: TOOLS }));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args = {} } = request.params;
  const { to, subject, body, cc, attachment_path } = args;

  // Validate common required fields
  const missing = ["to", "subject", "body"].filter((k) => !args[k]);
  if (missing.length) {
    return err(`Missing required argument(s): ${missing.join(", ")}`);
  }

  try {
    if (name === "send_email") {
      const result = await sendEmail({
        to, subject, body, cc,
        attachmentPath: attachment_path,
      });
      return ok(
        `Email sent successfully.\n` +
        `From       : ${result.from}\n` +
        `To         : ${to}\n` +
        `Subject    : ${subject}\n` +
        `Message ID : ${result.messageId}\n` +
        `Thread ID  : ${result.threadId}\n` +
        (attachment_path ? `Attachment : ${path.basename(attachment_path)}\n` : "")
      );
    }

    if (name === "draft_email") {
      const result = await draftEmail({
        to, subject, body, cc,
        attachmentPath: attachment_path,
      });
      return ok(
        `Email saved as Draft (NOT sent — awaiting your approval).\n` +
        `From       : ${result.from}\n` +
        `To         : ${to}\n` +
        `Subject    : ${subject}\n` +
        `Draft ID   : ${result.draftId}\n` +
        `Message ID : ${result.messageId ?? "N/A"}\n` +
        (attachment_path ? `Attachment : ${path.basename(attachment_path)}\n` : "") +
        `\nOpen Gmail > Drafts to review and send.`
      );
    }

    return err(`Unknown tool: "${name}". Available tools: send_email, draft_email`);

  } catch (e) {
    return err(`${name} failed: ${e.message}`);
  }
});

// ---------------------------------------------------------------------------
// Response helpers
// ---------------------------------------------------------------------------

function ok(text)  { return { content: [{ type: "text", text }] }; }
function err(text) { return { content: [{ type: "text", text }], isError: true }; }
function log(...a) { console.error("[email-mcp]", ...a); }

// ---------------------------------------------------------------------------
// Start (stdio transport)
// ---------------------------------------------------------------------------

const transport = new StdioServerTransport();
await server.connect(transport);
log("Server ready — send_email and draft_email tools available.");
