"""
FileSystemWatcher — Bronze-tier Inbox monitor.

Behavior:
  - Polls Inbox/ every 10 seconds.
  - On new file: copies it to Needs_Action/ with prefix FILE_
  - Creates a companion .md metadata file in Needs_Action/
  - Skips hidden files (dotfiles) and already-processed files.
  - All activity logged to console + Logs/filesystem_watcher.log

Usage:
    python watchers/filesystem_watcher.py
"""

import shutil
import signal
import sys
from datetime import datetime, timezone
from pathlib import Path

# Allow running from project root or from watchers/ directly
_HERE = Path(__file__).parent
_VAULT_ROOT = _HERE.parent

sys.path.insert(0, str(_HERE))
from base_watcher import BaseWatcher  # noqa: E402


VAULT_ROOT = _VAULT_ROOT
INBOX_DIR = VAULT_ROOT / "Inbox"
NEEDS_ACTION_DIR = VAULT_ROOT / "Needs_Action"
LOG_DIR = VAULT_ROOT / "Logs"
POLL_INTERVAL = 10  # seconds


class FileSystemWatcher(BaseWatcher):
    """
    Watches the Inbox folder and routes new files to Needs_Action.

    Processing rules:
      - Hidden files (starting with '.') are ignored.
      - A file is considered "already processed" if FILE_<name> exists
        in Needs_Action/ (safe to restart without duplicates).
      - Companion metadata saved as FILE_<stem>.meta.md
    """

    def __init__(self) -> None:
        super().__init__(
            watch_dir=INBOX_DIR,
            interval=POLL_INTERVAL,
            log_dir=LOG_DIR,
        )
        NEEDS_ACTION_DIR.mkdir(parents=True, exist_ok=True)
        self.logger.info("Vault root   : %s", VAULT_ROOT)
        self.logger.info("Watching     : %s", INBOX_DIR)
        self.logger.info("Destination  : %s", NEEDS_ACTION_DIR)
        self.logger.info("Poll interval: %ds", POLL_INTERVAL)

    # ------------------------------------------------------------------
    # Core logic
    # ------------------------------------------------------------------

    def process_file(self, file_path: Path) -> None:
        """Copy file to Needs_Action with FILE_ prefix + write metadata."""
        dest_name = f"FILE_{file_path.name}"
        dest_path = NEEDS_ACTION_DIR / dest_name

        # Guard: skip if already processed
        if dest_path.exists():
            self.logger.debug("Already processed, skipping: %s", file_path.name)
            return

        try:
            shutil.copy2(file_path, dest_path)
            self.logger.info("Copied  -> %s", dest_path.name)
        except OSError as exc:
            self.logger.error("Failed to copy %s: %s", file_path.name, exc)
            return

        self._write_metadata(file_path, dest_path)

    def _write_metadata(self, source: Path, dest: Path) -> None:
        """Create a companion .md metadata file in Needs_Action/."""
        meta_name = f"FILE_{source.stem}.meta.md"
        meta_path = NEEDS_ACTION_DIR / meta_name

        now = datetime.now(timezone.utc)
        stat = source.stat()
        size_kb = stat.st_size / 1024

        content = f"""\
---
source_file: {source.name}
destination: {dest.name}
detected_at: {now.strftime("%Y-%m-%d %H:%M:%S UTC")}
size_bytes: {stat.st_size}
status: needs_action
---

# Metadata — {source.name}

| Field        | Value                          |
|--------------|-------------------------------|
| Original     | `{source.name}`               |
| Copied As    | `{dest.name}`                 |
| Detected At  | {now.strftime("%Y-%m-%d %H:%M:%S UTC")} |
| Size         | {size_kb:.2f} KB              |
| Status       | needs_action                  |

## Action Required

Review `{dest.name}` in the `Needs_Action` folder and assign an owner.

---
*Auto-generated by FileSystemWatcher on {now.strftime("%Y-%m-%d")}.*
"""
        try:
            meta_path.write_text(content, encoding="utf-8")
            self.logger.info("Metadata -> %s", meta_name)
        except OSError as exc:
            self.logger.error("Failed to write metadata for %s: %s", source.name, exc)

    # ------------------------------------------------------------------
    # Poll loop
    # ------------------------------------------------------------------

    def _scan(self) -> None:
        """Single scan pass over the Inbox directory."""
        try:
            entries = sorted(INBOX_DIR.iterdir())
        except OSError as exc:
            self.logger.error("Cannot read Inbox: %s", exc)
            return

        files = [
            p for p in entries
            if p.is_file() and not p.name.startswith(".")
        ]

        if not files:
            self.logger.debug("Inbox empty — nothing to process.")
            return

        self.logger.info("Found %d file(s) in Inbox.", len(files))
        for file_path in files:
            self.process_file(file_path)

    def run(self) -> None:
        """Start the polling loop. Runs until stopped (Ctrl+C or SIGTERM)."""
        self._running = True
        self.logger.info("FileSystemWatcher started. Press Ctrl+C to stop.")

        while self._running:
            self.logger.debug("--- Poll cycle ---")
            self._scan()
            self._sleep()

        self.logger.info("FileSystemWatcher stopped.")


# ------------------------------------------------------------------
# Entry point
# ------------------------------------------------------------------

def _handle_signal(signum, frame):  # noqa: ANN001
    print("\n[watcher] Signal received, shutting down...")
    sys.exit(0)


if __name__ == "__main__":
    signal.signal(signal.SIGINT, _handle_signal)
    signal.signal(signal.SIGTERM, _handle_signal)

    watcher = FileSystemWatcher()
    watcher.run()
